# Deploy the site to AWS S3 on a push to the 'main' branch

name: Deploy S3

on:
  push:
    branches:
    - 'develop'

env:
  NODE: 14
  NODE_ENV: production
  DEPLOY_BUCKET: algorithm-publication-tool-staging
  DEPLOY_BUCKET_REGION: us-west-2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE }}

      - name: Cache node_modules
        uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}

      - name: Cache dist
        uses: actions/cache@v2
        id: cache-dist
        with:
          path: build
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.sha }}

      - name: Install
        run: yarn install

      - name: Build
        run: |
          export PUBLIC_URL='/apt'
          REACT_APP_FIGURES_BUCKET=nasa-apt-v5-prod-figures
          REACT_APP_S3_URI=http://s3.amazonaws.com
          REACT_APP_API_URL=https://apt.ds.io
          REACT_APP_AUTH_URL=https://apt.ds.io
          REACT_APP_FASTAPI_URL=https://apt.ds.io/fastapi
          yarn build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore dist cache
        uses: actions/cache@v2
        id: cache-dist
        with:
          path: build
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.sha }}

      - name: Serve site from subpath
        run: |
          mkdir deploy/
          mv build deploy/apt
          cp deploy/apt/index.html deploy/index.html

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ env.DEPLOY_BUCKET }}
          AWS_REGION: ${{ env.DEPLOY_BUCKET_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: ./deploy
