version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    environment:
      - PRODUCTION_BRANCH: develop

    steps:
      - run:
          name: Install AWS CLI
          command: sudo apt-get -y -qq install awscli

      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: v1-dependencies-{{ checksum ".circleci/config.yml" }}-{{ checksum "package.json" }}

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum ".circleci/config.yml" }}-{{ checksum "package.json" }}

      - run:
          name: Build collecticons
          command: yarn collecticons

      - run:
          name: Lint
          command: yarn lint

      - run:
          name: Building site
          command: |
            if [ "${CIRCLE_BRANCH}" == "${PRODUCTION_BRANCH}" ]; then
              yarn build           
            else
              echo "Skip building site"
            fi

      - run:
          name: Deploy to Surge
          command: |
            if [ "${CIRCLE_BRANCH}" == "${PRODUCTION_BRANCH}" ]; then
              cp ./build/index.html ./build/200.html
              ./node_modules/surge/lib/cli.js --project ./build --domain nasa-apt-dev.surge.sh
            else
              echo "Not the branch you're looking for, skipping deploy"
            fi

