name: Build and publish docker image

on:
  push:
    branches:
      - develop
    paths-ignore:
      - "adr/**"
      - "cypress/**"
      - "docs/**"
      - ".vscode/**"

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build development image
        run: docker build -t ghcr.io/NASA-IMPACT/nasa-apt-frontend:develop .

      - name: Push docker image
        run: docker push ghcr.io/NASA-IMPACT/nasa-apt-frontend:develop