# Deploy the site to AWS S3 on a push to specific branches

name: Deploy Production - UAH (S3)

on:
  push:
    branches:
    - 'main'

env:
  NODE: 14
  DOMAIN_UAH: https://impact.earthdata.nasa.gov/apt
  DEPLOY_BUCKET_UAH: algorithm-publication-tool-staging
  DEPLOY_BUCKET_UAH_REGION: us-west-2
  # Variables needed to override the production config specific to UAH
  AUTH_REGION: us-east-2
  AUTH_POOL_ID: us-east-2_dsHdmbBUK
  AUTH_CLIENT_ID: 66kd4hhbm7cb5suifelj34btki
  AUTH_UI: https://nasa-apt-api-lambda-prod.auth.us-east-2.amazoncognito.com

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE }}

      - name: Cache node_modules
        uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}

      - name: Cache dist
        uses: actions/cache@v2
        id: cache-dist
        with:
          path: dist
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.sha }}

      - name: Install
        run: yarn install

      - name: Build production
        run: PUBLIC_URL="${{ env.DOMAIN_UAH }}" yarn build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore node_modules
        uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}

      - name: Restore dist cache
        uses: actions/cache@v2
        id: cache-dist
        with:
          path: dist
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.sha }}

      - name: Use Node.js ${{ env.NODE }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE }}

      - name: Serve site from subpath
        run: |
          mkdir deploy/
          mv dist deploy/apt
          cp deploy/apt/index.html deploy/index.html

      - name: Deploy to S3 Production
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ env.DEPLOY_BUCKET_UAH }}
          AWS_REGION: ${{ env.DEPLOY_BUCKET_UAH_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: ./deploy