name: Deploy Staging

on:
  push:
    branches:
      - 'develop'

env:
  NODE_VERSION: 14
  DOMAIN_STAGING: https://d3p0lkft682kz.cloudfront.net
  DEPLOY_BUCKET_STAGING: nasa-apt-v5-staging
  DEPLOY_BUCKET_STAGING_REGION: us-east-1
  STAGING_CLOUDFRONT_DISTRIBUTION_ID: E2XF0H60GJHF3E
  OIDC_ROLE: arn:aws:iam::552819999234:role/nasa-apt-frontend-ci

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@01ce38bf961b4e243a6342cbade0dbc8ba3f0432 # 0.12.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache dependencies
        uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3
        with:
          path: ~/.yarn
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build staging
        run: PUBLIC_URL="${{ env.DOMAIN_STAGING }}" yarn stage

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4
        with:
          role-to-assume: ${{ env.OIDC_ROLE }}
          aws-region: ${{ env.DEPLOY_BUCKET_STAGING_REGION }}

      - name: Deploy to S3
        run: |
          aws s3 sync ./dist s3://${{ env.DEPLOY_BUCKET_STAGING }} \
            --delete \
            --follow-symlinks

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.STAGING_CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
